StyleStock.web/Models/ErrorViewModel.cs
namespace StyleStock.web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StyleStock.web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StyleStock.web.Models;
using System.Diagnostics;

namespace StyleStock.web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StyleStock.web/Controllers/SuppliersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using StyleStock.Domain;
using StyleStock.Domain.DTOS;
using StyleStock.Domain.Entities;

namespace StyleStock.web.Controllers
{
	public class SuppliersController : Controller
	{
		private readonly StyleStockDbContext _context;

		public SuppliersController(StyleStockDbContext context)
		{
			_context = context;
		}
		public async Task<IActionResult> Index()
		{

			List<Suppliers> suppliers = await _context.Suppliers.ToListAsync();

			return View(suppliers);

		}

		[HttpGet]
		public IActionResult CreateSuppliers()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> CreateSuppliers(CreateSuppliersDTO supplierDTO)
		{
			if (!ModelState.IsValid || ModelState.IsNullOrEmpty())
			{
				return View(supplierDTO);
			}

			Suppliers newSupplier = new Suppliers
			{
				Name = supplierDTO.Name,
				Phone = supplierDTO.Phone,
				Email = supplierDTO.Email,
				Adress = supplierDTO.Adress
			};


			_context.Suppliers.Add(newSupplier);
			await _context.SaveChangesAsync();


			return RedirectToAction(nameof(Index));

		}

		[HttpGet]
		public async Task<IActionResult> SuppliersEdit(int id)
		{
			var supplier = await _context.Suppliers.FirstOrDefaultAsync(s => s.SupplierID == id);

			if (supplier == null)
			{
				return NotFound();
			}

			var updateSuppliersDTO = new UpdateSuppliersDTO
			{
				SupplierID = supplier.SupplierID,
				Name = supplier.Name,
				Phone = supplier.Phone,
				Email = supplier.Email,
				Adress = supplier.Adress
			};

			return View(updateSuppliersDTO);
		}

		[HttpPost]
		public async Task<IActionResult> SuppliersEdit(UpdateSuppliersDTO updateSuppliers)
		{
			if (!ModelState.IsValid)
			{
				return View(updateSuppliers);
			}

			var supplier = await _context.Suppliers.FindAsync(updateSuppliers.SupplierID);

			if (supplier == null)
			{
				return NotFound();
			}

			supplier.Name = updateSuppliers.Name;
			supplier.Phone = updateSuppliers.Phone;
			supplier.Email = updateSuppliers.Email;
			supplier.Adress = updateSuppliers.Adress;

			_context.Suppliers.Update(supplier);
			await _context.SaveChangesAsync();

			return RedirectToAction(nameof(Index));

		}

		[HttpGet]
		public async Task<IActionResult> SuppliersDelete (int id)
		{
			var supplier = await _context.Suppliers.FirstOrDefaultAsync(s => s.SupplierID == id);

			if (supplier == null)
			{
				return NotFound();
			}
			_context.Suppliers.Remove(supplier);
			await _context.SaveChangesAsync();


			return RedirectToAction(nameof(Index));
		}

	}
}

StyleStock.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StyleStock.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StyleStock.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StyleStock.web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StyleStock.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - StyleStock.web - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StyleStock.web/Views/Suppliers/CreateSuppliers.cshtml
@using StyleStock.Domain.DTOS
@model CreateSuppliersDTO
@{
	ViewData["Title"] = "Agregar Suplidor";
}

<div class="row">
	<div class="col-6 ">
		<h2>Nuevo Suplidor</h2>
		<form asp-controller="Suppliers" asp-action="CreateSuppliers" method="post">
			<div class="mb-2">
				<lable for="name" class="form-label">Nombre Suplidor</lable>
				<input class="form-control" asp-for="Name" id="name" type="text" placeholder="Nombre" required/>
			</div>

			<div class="mb-2">
				<lable for="phone" class="form-label">Telefono del suplidor</lable>
				<input class="form-control" asp-for="Phone" id="phone" type="text" placeholder="Telefono" required />
			</div>

			<div class="mb-2">
				<lable for="email" class="form-label">Correo electronico del suplidor</lable>
				<input class="form-control" asp-for="Email" id="email" type="text" placeholder="Correo Electronico" required />
			</div>

			<div class="mb-2">
				<lable for="adress" class="form-label">Direccion del suplidor</lable>
				<input class="form-control" asp-for="Adress" id="adress" type="text" placeholder="Direccion"  required/>
			</div>

			<div class="mb-3">
				<button class="btn btn-primary" type="submit">Guardar</button>
				<a asp-controller="Suppliers" asp-action="Index" class="btn btn-danger">Cancelar</a>
			</div>
		</form>
	</div>
</div>

StyleStock.web/Views/Suppliers/Index.cshtml
@using StyleStock.Domain.Entities
@model List<Suppliers>

@{
    ViewData["Title"] = "Suplidores";
}

<div class="row">
    <div class="col-8">
        <h2>Lista de Suplidores</h2>
        <table class="table table-bordered">
            <a asp-controller="Suppliers" asp-action="CreateSuppliers" class="btn btn-success mb-3">Nuevo Suplidor</a>
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Telefono</th>
                    <th scope="col">Email</th>
                    <th scope="col">Direccion</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.SupplierID</td>
                        <td>@item.Name</td>
                        <td>@item.Phone</td>
                        <td>@item.Email</td>
                        <td>@item.Adress</td>

                        <td>
                            <a asp-controller="Suppliers"
                               asp-action="SuppliersEdit"
                               asp-route-id="@item.SupplierID"
                               class="btn btn-primary mb-3">
                                Editar
                            </a>
                        </td>

                        <td>
                            <a asp-controller="Suppliers"
                               asp-action="SuppliersDelete"
                               asp-route-id="@item.SupplierID"
                               onclick="return Confirmar()"
                               class="btn btn-danger mb-3">
                                Eliminar
                            </a>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


@section Scripts{
	<script>
		function Confirmar() {
			return confirm("Esta seguro que desea elimimar?")
		}
	</script>
}

StyleStock.web/Views/Suppliers/SuppliersEdit.cshtml
@using StyleStock.Domain.DTOS
@model UpdateSuppliersDTO
@{
	ViewData["Title"] = "Modificar Suplidor";
}

<div class="row">
	<div class="col-6">
		<h2>Modificar Suplidor</h2>


		<form asp-controller="Suppliers" asp-action="SuppliersEdit" method="post">


			<input type="hidden" asp-for="SupplierID" />

			<div class="mb-2">
				<label for="name" class="form-label">Nombre del Suplidor</label>
				<input class="form-control" asp-for="Name" id="name" type="text" placeholder="Nombre" required />
			</div>

			<div class="mb-2">
				<label for="phone" class="form-label">Teléfono del Suplidor</label>
				<input class="form-control" asp-for="Phone" id="phone" type="text" placeholder="Teléfono" required />
			</div>

			<div class="mb-2">
				<label for="email" class="form-label">Correo Electrónico del Suplidor</label>
				<input class="form-control" asp-for="Email" id="email" type="email" placeholder="Correo Electrónico" required />
			</div>

			<div class="mb-2">
				<label for="address" class="form-label">Dirección del Suplidor</label>
				<input class="form-control" asp-for="Adress" id="address" type="text" placeholder="Dirección" required />
			</div>

			<div class="mb-3">
				<button class="btn btn-primary" type="submit">Guardar</button>
				<a asp-controller="Suppliers" asp-action="Index" class="btn btn-danger">Cancelar</a>
			</div>
		</form>
	</div>
</div>